### ISSUE TITLE
used tool is broken

### ISSUE THREAD

**Issue by ZuRiKanHD** [JakeGBLP/Lusk#18] opened 2024-12-27 10:10 UTC
**Describe the bug**
The extension https://skripthub.net/docs/?id=11909 isn't working correctly.

It always returns the main hand slot, even when the offhand slot is used.

In this specific case, it's about the event "on rightclick". Even if the item from the offhand is used, the extension still provides information from the main hand slot.

**To Reproduce**
Take bone meal in the offhand and leave the main hand empty (air).

`on right click:
message "%used tool%, %hand%"`

**Expected behavior**
The extension provides information from the offhand.

**/sk info:**
![image](https://github.com/user-attachments/assets/14cee654-0804-4422-82da-38d32f891a5d)
![image](https://github.com/user-attachments/assets/c414a89e-c19a-47e7-8c21-b9c10e3e6337)

**Comment by JakeGBLP** [comment] 2024-12-27 11:09
This is somewhat of a skript issue, a bug and intended behavior at the same time, when you right click the sever prioritizes the main hand, when you right click both hands send the interact event, skript, however, keeps only the first one; I can see if there's a way to fix this on Lusk's end but I can't guarantee success, I'll keep you posted.

**Comment by JakeGBLP** [comment] 2024-12-29 10:16
This has been resolved by adding the Interact event which is a glorified right click event that supports both hands as well as more things, this replaces the example you've provided in this issue:
```
on player interact:
  message "%used tool%, %hand%"
```

**Closed** 2024-12-29 10:16 UTC
Labels: bug, enhancement, good first issue, Skript Issue, Completed
